name: Natours Project CI/CD pipeline
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: npm install, build, and test
        run: npm install
